// SPDX-License-Identifier: Apache-2.0
/*
 * Copyright (c) 2026 Sunnyside Labs Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Originally generated by gnark (https://github.com/consensys/gnark)
 * Modified by Sunnyside Labs Inc.
 */
pragma solidity 0.8.34;

import {Groth16Verifier} from "./Groth16Verifier.sol";

/// @title Groth16GiftClaimVerifier
/// @notice Groth16 verifier scaffold for Claimable Transfer gift claim proofs with multi-batchSize
///         support. A gift claim epoch is a batch of single-input/single-output re-mints, so it is
///         parameterized by a single batch-size value (mirroring Groth16DepositVerifier), NOT the
///         multi-dimensional epoch verifier shape.
/// @dev SCAFFOLD ONLY. This contract carries no verifying key. The real verifying key for the gift
///      claim circuit is produced by the trusted-setup ceremony (a Groth16 per-circuit VK), which is
///      OUT OF SCOPE for this change. The ceremony output is registered post-deployment via
///      `registerVK(batchSize, ...)` on the inherited `Groth16Verifier`. Until a VK is registered for
///      a given batchSize, `verifyGiftClaim` reverts with `VerifyingKeyNotFound` — it never returns a
///      false "valid". Wiring `submitGiftClaimEpoch` / `publicGiftExit` and the
///      contract-side public-input builder is also out of scope here.
/// @custom:security-contact contact@sunnyside.io
contract Groth16GiftClaimVerifier is Groth16Verifier {
    constructor(address initialOwner) Groth16Verifier(initialOwner) {}

    /// @notice Verify a gift claim proof for a specific batch size
    /// @param batchSize The batch size (max gift claims) of this gift claim epoch
    /// @param proof Groth16 proof [A.x, A.y, B.x1, B.x0, B.y1, B.y0, C.x, C.y]
    /// @param publicInputs Public inputs to the circuit
    /// @return True if proof is valid
    function verifyGiftClaim(uint32 batchSize, uint256[8] calldata proof, uint256[] calldata publicInputs)
        external
        view
        returns (bool)
    {
        // Suppress unused variable warning - proof is read via calldataload at proofOffset
        proof;

        VKPointers storage vk = vkRegistry[batchSize];
        if (vk.vkConstants == address(0)) revert VerifyingKeyNotFound();

        // Calldata layout: selector (4) + batchSize (32) + proof starts at 0x24
        _verifyProof(0x24, publicInputs, vk);
        return true;
    }

    /// @notice Whether a verifying key is registered for the given batch size
    /// @dev Non-reverting mirror of the VerifyingKeyNotFound condition in verifyGiftClaim, so a caller can
    ///      check VK presence before proving/verifying. Until the ceremony registers a VK for a batchSize,
    ///      this returns false (and verifyGiftClaim would revert VerifyingKeyNotFound for that batchSize).
    /// @param batchSize The batch size (max gift claims) to check
    /// @return True if a verifying key is registered for batchSize
    function hasVerifyingKey(uint32 batchSize) external view returns (bool) {
        return vkRegistry[batchSize].vkConstants != address(0);
    }
}
