// SPDX-License-Identifier: Apache-2.0
/*
 * Copyright (c) 2026 Sunnyside Labs Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Originally generated by gnark (https://github.com/consensys/gnark)
 * Modified by Sunnyside Labs Inc.
 */
pragma solidity 0.8.34;

import {Groth16Verifier} from "./Groth16Verifier.sol";

/// @title Groth16PortalDepositVerifier
/// @notice Groth16 verifier for hidden-recipient portal-deposit proofs (DepositPortalCircuit),
///         with multi-batchSize support via the shared SSTORE2 VK registry.
/// @dev A SEPARATE verifier from Groth16DepositVerifier because the portal circuit has its own
///      verifying key and its own public-input layout (E, counter, H, tokenId, amount, commitment
///      per slot — no caller-supplied commitments hash). The abstract Groth16Verifier base and its
///      registerVK path are reused unchanged; only the entrypoint's calldata layout differs.
/// @custom:security-contact contact@sunnyside.io
contract Groth16PortalDepositVerifier is Groth16Verifier {
    constructor(address initialOwner) Groth16Verifier(initialOwner) {}

    /// @notice Verify a portal-deposit proof for a specific batch size
    /// @param batchSize The portal-deposit circuit's batch size (one slot per portal deposit)
    /// @param proof Groth16 proof [A.x, A.y, B.x1, B.x0, B.y1, B.y0, C.x, C.y]
    /// @param publicInputs Public inputs to the circuit, in buildPortalDepositInputs layout order
    /// @return True if proof is valid
    function verifyPortalDeposit(uint32 batchSize, uint256[8] calldata proof, uint256[] calldata publicInputs)
        external
        view
        returns (bool)
    {
        // Suppress unused variable warning - proof is read via calldataload at proofOffset.
        proof;

        VKPointers storage vk = vkRegistry[batchSize];
        if (vk.vkConstants == address(0)) revert VerifyingKeyNotFound();

        // Calldata layout: selector (4) + batchSize (32) + proof starts at 0x24, identical to
        // verifyDeposit — the only difference between the two verifiers is which VK is registered.
        _verifyProof(0x24, publicInputs, vk);
        return true;
    }
}
